// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ctkuhsitqmcqbpktmnqw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImN0a3Voc2l0cW1jcWJwa3RtbnF3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA2MjMyMjUsImV4cCI6MjA2NjE5OTIyNX0.lGLkPFDoV86pzKuHnCGPcvvLVfffS5VDlOs4d__njTA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);